### ISSUE TITLE
Couenne does not compile with gcc 4.7.2

### ISSUE THREAD

**Issue by svigerske** [coin-or-tools/BuildTools#110]
Issue created by migration from Trac.

Original creator: fmargot

Original creation time: 2014-03-18 12:46:58

Assignee: @svigerske

Version: 0.7

Hi:

After doing a V_PATH configuration et compiling couenne-trunk with
gcc version 4.7.2 20121109 (Red Hat 4.7.2-8) (GCC) on
Fedora release 18 (Spherical Cow) using:

../configure -C
make install

I get:
ClpSimplexDual.o
In file included from ../../../Clp/src/ClpConfig.h:28:0,
                 from ../../../Clp/src/ClpModel.hpp:9,
                 from ../../../Clp/src/ClpSimplex.hpp:16,
                 from ../../../Clp/src/ClpSimplexDual.hpp:14,
                 from ../../../Clp/src/ClpSimplexDual.cpp:101:
./config.h:85:0: error: "HAVE_CMATH" redefined
In file included from ../../../Clp/src/ClpSimplexDual.cpp:100:0:
../../../Clp/src/ClpHelperFunctions.hpp:10:0: note: this is the location of the previous definition

The only fix I could find is to modify Clp/src/config.h as follows:

#ifndef HAVE_CMATH                                                              
#define HAVE_CMATH 1                                                            
#endif                                                                          
 
Francois

**Comment by svigerske** [comment]
Comment by @svigerske created at 2014-03-18 13:33:15

I don't understand this error message.

[ClpHelperFunctions.hpp:10](https://projects.coin-or.org/Clp/browser/releases/1.15.6/Clp/src/ClpHelperFunctions.hpp) has only a `#ifdef HAVE_CMATH`, no `#define HAVE_CMATH`.

Can you check that you have a clean checkout?

**Comment by svigerske** [comment]
Comment by @svigerske created at 2017-07-25 15:41:56

No response from reporter for 3 years. Closing ticket.

**Comment by svigerske** [comment]
Comment by @svigerske created at 2017-07-25 15:41:56

Resolution: worksforme
